//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScream
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchanx
    {
        public int Id { get; set; }
        public Nullable<int> Num { get; set; }
        public string Abbr { get; set; }
        public string Name { get; set; }
    }
}
