//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScream
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPIndustry
    {
        public string Symbol { get; set; }
        public int IndustryID { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<float> NumStock { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<float> CurrentPrice { get; set; }
        public Nullable<float> pc1w { get; set; }
        public Nullable<int> r1w { get; set; }
        public Nullable<float> pc2w { get; set; }
        public Nullable<int> r2w { get; set; }
        public Nullable<float> pc3w { get; set; }
        public Nullable<int> r3w { get; set; }
        public Nullable<float> pc4w { get; set; }
        public Nullable<int> r4w { get; set; }
        public Nullable<float> pc13w { get; set; }
        public Nullable<int> r13w { get; set; }
        public Nullable<float> pc26w { get; set; }
        public Nullable<int> r26w { get; set; }
        public Nullable<float> pc52w { get; set; }
        public Nullable<int> r52w { get; set; }
        public Nullable<float> v1 { get; set; }
        public Nullable<float> v2 { get; set; }
        public Nullable<float> v3 { get; set; }
        public Nullable<float> v4 { get; set; }
        public Nullable<float> v5 { get; set; }
        public Nullable<float> v6 { get; set; }
        public Nullable<float> v7 { get; set; }
        public Nullable<float> v8 { get; set; }
        public Nullable<float> v9 { get; set; }
        public Nullable<float> v10 { get; set; }
        public Nullable<float> a5v1 { get; set; }
        public Nullable<float> a5v2 { get; set; }
        public Nullable<float> a5v3 { get; set; }
        public Nullable<float> a5v4 { get; set; }
        public Nullable<float> a5v5 { get; set; }
        public Nullable<float> a5v6 { get; set; }
        public Nullable<float> a5v7 { get; set; }
        public Nullable<float> a5v8 { get; set; }
        public Nullable<float> a5v9 { get; set; }
        public Nullable<float> a5v10 { get; set; }
        public Nullable<float> a10v1 { get; set; }
        public Nullable<float> a10v2 { get; set; }
        public Nullable<float> a10v3 { get; set; }
        public Nullable<float> a10v4 { get; set; }
        public Nullable<float> a10v5 { get; set; }
        public Nullable<float> a10v6 { get; set; }
        public Nullable<float> a10v7 { get; set; }
        public Nullable<float> a10v8 { get; set; }
        public Nullable<float> a10v9 { get; set; }
        public Nullable<float> a10v10 { get; set; }
    }
}
