//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScream
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectedStock
    {
        public string Symbol { get; set; }
        public Nullable<int> Index { get; set; }
        public string IndustryID { get; set; }
        public string SectorID { get; set; }
        public string Type { get; set; }
        public string DateSelected { get; set; }
        public Nullable<float> PriceSelected { get; set; }
        public Nullable<int> VolumeSelected { get; set; }
        public Nullable<int> Avg5dVol { get; set; }
        public Nullable<int> QuantityBid { get; set; }
        public Nullable<float> PriceBid { get; set; }
        public Nullable<float> StopBuy { get; set; }
        public Nullable<float> StopLossBuy { get; set; }
        public Nullable<float> MRC { get; set; }
        public Nullable<float> PETTM { get; set; }
        public Nullable<float> PETTMInd { get; set; }
        public Nullable<float> PETTMSec { get; set; }
        public Nullable<float> SMRQv1Y { get; set; }
        public Nullable<float> SMRQv1YInd { get; set; }
        public Nullable<float> SMRQv1YSec { get; set; }
        public Nullable<float> STTMv1Y { get; set; }
        public Nullable<float> STTMv1YInd { get; set; }
        public Nullable<float> STTMv1YSec { get; set; }
        public Nullable<int> r1w { get; set; }
        public Nullable<int> r2w { get; set; }
        public Nullable<int> r3w { get; set; }
        public Nullable<int> r4w { get; set; }
        public Nullable<int> r13w { get; set; }
        public Nullable<int> r26w { get; set; }
        public Nullable<int> r52w { get; set; }
        public Nullable<int> NumStockInd { get; set; }
        public Nullable<int> r1wInd { get; set; }
        public Nullable<int> r2wInd { get; set; }
        public Nullable<int> r3wInd { get; set; }
        public Nullable<int> r4wInd { get; set; }
        public Nullable<int> r13wInd { get; set; }
        public Nullable<int> r26wInd { get; set; }
        public Nullable<int> r52wInd { get; set; }
        public Nullable<int> NumStockSec { get; set; }
        public Nullable<int> r1wSec { get; set; }
        public Nullable<int> r2wSec { get; set; }
        public Nullable<int> r3wSec { get; set; }
        public Nullable<int> r4wSec { get; set; }
        public Nullable<int> r13wSec { get; set; }
        public Nullable<int> r26wSec { get; set; }
        public Nullable<int> r52wSec { get; set; }
    }
}
