//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScream.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectorFinancial
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<float> GRCapitalSpending5YrGrowthRate { get; set; }
        public Nullable<float> GREPS5YrGrowthRate { get; set; }
        public Nullable<float> GREPSTTMvsTTM1YrAgo { get; set; }
        public Nullable<float> GREPSMRQvsQtr1YrAgo { get; set; }
        public Nullable<float> GRSales5YrGrowthRate { get; set; }
        public Nullable<float> GRSalesTTMvsTTM1YrAgo { get; set; }
        public Nullable<float> GRSalesMRQvsQtr1YrAgo { get; set; }
        public Nullable<float> MEReturnonEquity5YrAvg { get; set; }
        public Nullable<float> MEReturnonEquityTTM { get; set; }
        public Nullable<float> MEReturnonInvestment5YrAvg { get; set; }
        public Nullable<float> MEReturnonInvestmentTTM { get; set; }
        public Nullable<float> MEReturnonAssets5YrAvg { get; set; }
        public Nullable<float> MEReturnonAssetsTTM { get; set; }
        public Nullable<float> PREffectiveTaxRate5YrAvg { get; set; }
        public Nullable<float> PREffectiveTaxRateTTM { get; set; }
        public Nullable<float> PRNetProfitMargin5YrAvg { get; set; }
        public Nullable<float> PRNetProfitMarginTTM { get; set; }
        public Nullable<float> PRPreTaxMargin5YrAvg { get; set; }
        public Nullable<float> PRPreTaxMarginTTM { get; set; }
        public Nullable<float> PROperatingMargin5YrAvg { get; set; }
        public Nullable<float> PROperatingMarginTTM { get; set; }
        public Nullable<float> PREBITD5YrAvg { get; set; }
        public Nullable<float> PREBITDMarginTTM { get; set; }
        public Nullable<float> PRGrossMargin5YrAvg { get; set; }
        public Nullable<float> PRGrossMarginTTM { get; set; }
        public Nullable<float> EffAssetTurnoverTTM { get; set; }
        public Nullable<float> EffInventoryTurnoverTTM { get; set; }
        public Nullable<float> EffReceivableTurnoverTTM { get; set; }
        public Nullable<float> EffNetIncomeEmployeeTTM { get; set; }
        public Nullable<float> EffRevenueEmployeeTTM { get; set; }
        public Nullable<float> DivPayoutRatioTTM { get; set; }
        public Nullable<float> DivDividend5YearGrowthRate { get; set; }
        public Nullable<float> DivDividendYield5YearAvg { get; set; }
        public Nullable<float> DivDividendYield { get; set; }
        public Nullable<float> FSInterestCoverageTTM { get; set; }
        public Nullable<float> FSTotalDebttoEquityMRQ { get; set; }
        public Nullable<float> FSLTDebttoEquityMRQ { get; set; }
        public Nullable<float> FSCurrentRatioMRQ { get; set; }
        public Nullable<float> FSQuickRatioMRQ { get; set; }
        public Nullable<float> VROwnedInstitutions { get; set; }
        public Nullable<float> VRPricetoCashFlowTTM { get; set; }
        public Nullable<float> VRPricetoTangibleBookMRQ { get; set; }
        public Nullable<float> VRPricetoBookMRQ { get; set; }
        public Nullable<float> VRPricetoSalesTTM { get; set; }
        public Nullable<float> VRBeta { get; set; }
        public Nullable<float> VRPELowLast5Yrs { get; set; }
        public Nullable<float> VRPEHighLast5Yrs { get; set; }
        public Nullable<float> VRPERatioTTM { get; set; }
    }
}
