//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScream.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAnalyst
    {
        public string Symbol { get; set; }
        public Nullable<float> IHSharesOwned { get; set; }
        public Nullable<float> IHofHolders { get; set; }
        public Nullable<float> IHTotalSharesHeld { get; set; }
        public Nullable<float> IH3MoNetChange { get; set; }
        public Nullable<float> IHNewPositions { get; set; }
        public Nullable<float> IHClosedPositions { get; set; }
        public Nullable<float> IHIncreasedPositions { get; set; }
        public Nullable<float> IHReducedPositions { get; set; }
        public Nullable<float> IHNetBuyers { get; set; }
        public string CRConsensusRecommendation { get; set; }
        public Nullable<float> CRNextEarningsapprox { get; set; }
        public string CRCompanyFiscalYearEndMonth { get; set; }
        public string CRLastUpdated { get; set; }
        public Nullable<float> ARRMeanRatingCurrent { get; set; }
        public Nullable<float> ARRMeanRating1MonthAgo { get; set; }
        public Nullable<float> ARRMeanRating2MonthAgo { get; set; }
        public Nullable<float> ARRMeanRating3MonthAgo { get; set; }
        public string HSSurpiseQuarter { get; set; }
        public Nullable<float> HSSalesSurpriseQuater0 { get; set; }
        public Nullable<float> HSSalesSurpriseQuater1 { get; set; }
        public Nullable<float> HSSalesSurpriseQuater2 { get; set; }
        public Nullable<float> HSSalesSurpriseQuater3 { get; set; }
        public Nullable<float> HSSalesSurpriseQuater4 { get; set; }
        public Nullable<float> HSEPSSurpriseQuater0 { get; set; }
        public Nullable<float> HSEPSSurpriseQuater1 { get; set; }
        public Nullable<float> HSEPSSurpriseQuater2 { get; set; }
        public Nullable<float> HSEPSSurpriseQuater3 { get; set; }
        public Nullable<float> HSEPSSurpriseQuater4 { get; set; }
        public Nullable<float> CETSaleQuarterCurrent0 { get; set; }
        public Nullable<float> CETSaleQuarter1WeekAgo0 { get; set; }
        public Nullable<float> CETSaleQuarter1MonthAgo0 { get; set; }
        public Nullable<float> CETSaleQuarter2MonthAgo0 { get; set; }
        public Nullable<float> CETSaleQuarter1YearAgo0 { get; set; }
        public Nullable<float> CETSaleQuarterCurrent1 { get; set; }
        public Nullable<float> CETSaleQuarter1WeekAgo1 { get; set; }
        public Nullable<float> CETSaleQuarter1MonthAgo1 { get; set; }
        public Nullable<float> CETSaleQuarter2MonthAgo1 { get; set; }
        public Nullable<float> CETSaleQuarter1YearAgo1 { get; set; }
        public Nullable<float> CETSaleQuarterCurrent2 { get; set; }
        public Nullable<float> CETSaleQuarter1WeekAgo2 { get; set; }
        public Nullable<float> CETSaleQuarter1MonthAgo2 { get; set; }
        public Nullable<float> CETSaleQuarter2MonthAgo2 { get; set; }
        public Nullable<float> CETSaleQuarter1YearAgo2 { get; set; }
        public Nullable<float> CETSaleQuarterCurrent3 { get; set; }
        public Nullable<float> CETSaleQuarter1WeekAgo3 { get; set; }
        public Nullable<float> CETSaleQuarter1MonthAgo3 { get; set; }
        public Nullable<float> CETSaleQuarter2MonthAgo3 { get; set; }
        public Nullable<float> CETSaleQuarter1YearAgo3 { get; set; }
        public Nullable<float> CETSaleQuarterCurrent4 { get; set; }
        public Nullable<float> CETSaleQuarter1WeekAgo4 { get; set; }
        public Nullable<float> CETSaleQuarter1MonthAgo4 { get; set; }
        public Nullable<float> CETSaleQuarter2MonthAgo4 { get; set; }
        public Nullable<float> CETSaleQuarter1YearAgo4 { get; set; }
        public Nullable<float> CETSaleYearCurrent0 { get; set; }
        public Nullable<float> CETSaleYear1WeekAgo0 { get; set; }
        public Nullable<float> CETSaleYear1MonthAgo0 { get; set; }
        public Nullable<float> CETSaleYear2MonthAgo0 { get; set; }
        public Nullable<float> CETSaleYear1YearAgo0 { get; set; }
        public Nullable<float> CETSaleYearCurrent1 { get; set; }
        public Nullable<float> CETSaleYear1WeekAgo1 { get; set; }
        public Nullable<float> CETSaleYear1MonthAgo1 { get; set; }
        public Nullable<float> CETSaleYear2MonthAgo1 { get; set; }
        public Nullable<float> CETSaleYear1YearAgo1 { get; set; }
        public Nullable<float> CETSaleYearCurrent2 { get; set; }
        public Nullable<float> CETSaleYear1WeekAgo2 { get; set; }
        public Nullable<float> CETSaleYear1MonthAgo2 { get; set; }
        public Nullable<float> CETSaleYear2MonthAgo2 { get; set; }
        public Nullable<float> CETSaleYear1YearAgo2 { get; set; }
        public Nullable<float> CETEarningQuarterCurrent0 { get; set; }
        public Nullable<float> CETEarningQuarter1WeekAgo0 { get; set; }
        public Nullable<float> CETEarningQuarter1MonthAgo0 { get; set; }
        public Nullable<float> CETEarningQuarter2MonthAgo0 { get; set; }
        public Nullable<float> CETEarningQuarter1YearAgo0 { get; set; }
        public Nullable<float> CETEarningQuarterCurrent1 { get; set; }
        public Nullable<float> CETEarningQuarter1WeekAgo1 { get; set; }
        public Nullable<float> CETEarningQuarter1MonthAgo1 { get; set; }
        public Nullable<float> CETEarningQuarter2MonthAgo1 { get; set; }
        public Nullable<float> CETEarningQuarter1YearAgo1 { get; set; }
        public Nullable<float> CETEarningQuarterCurrent2 { get; set; }
        public Nullable<float> CETEarningQuarter1WeekAgo2 { get; set; }
        public Nullable<float> CETEarningQuarter1MonthAgo2 { get; set; }
        public Nullable<float> CETEarningQuarter2MonthAgo2 { get; set; }
        public Nullable<float> CETEarningQuarter1YearAgo2 { get; set; }
        public Nullable<float> CETEarningQuarterCurrent3 { get; set; }
        public Nullable<float> CETEarningQuarter1WeekAgo3 { get; set; }
        public Nullable<float> CETEarningQuarter1MonthAgo3 { get; set; }
        public Nullable<float> CETEarningQuarter2MonthAgo3 { get; set; }
        public Nullable<float> CETEarningQuarter1YearAgo3 { get; set; }
        public Nullable<float> CETEarningQuarterCurrent4 { get; set; }
        public Nullable<float> CETEarningQuarter1WeekAgo4 { get; set; }
        public Nullable<float> CETEarningQuarter1MonthAgo4 { get; set; }
        public Nullable<float> CETEarningQuarter2MonthAgo4 { get; set; }
        public Nullable<float> CETEarningQuarter1YearAgo4 { get; set; }
        public Nullable<float> CETEarningYearCurrent0 { get; set; }
        public Nullable<float> CETEarningYear1WeekAgo0 { get; set; }
        public Nullable<float> CETEarningYear1MonthAgo0 { get; set; }
        public Nullable<float> CETEarningYear2MonthAgo0 { get; set; }
        public Nullable<float> CETEarningYear1YearAgo0 { get; set; }
        public Nullable<float> CETEarningYearCurrent1 { get; set; }
        public Nullable<float> CETEarningYear1WeekAgo1 { get; set; }
        public Nullable<float> CETEarningYear1MonthAgo1 { get; set; }
        public Nullable<float> CETEarningYear2MonthAgo1 { get; set; }
        public Nullable<float> CETEarningYear1YearAgo1 { get; set; }
        public Nullable<float> CETEarningYearCurrent2 { get; set; }
        public Nullable<float> CETEarningYear1WeekAgo2 { get; set; }
        public Nullable<float> CETEarningYear1MonthAgo2 { get; set; }
        public Nullable<float> CETEarningYear2MonthAgo2 { get; set; }
        public Nullable<float> CETEarningYear1YearAgo2 { get; set; }
    }
}
